name: Validate

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
          cache: pip

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Install Dependencies
        run: pip-sync requirements.txt
        if: steps.cache_dependencies.outputs.cache-hit != 'true'

      - name: Flake8
        run: flake8 src tests

      - name: Pylint
        run: pylint src tests

      - name: Pytest
        run: pytest --cov=src tests/ -n auto
